// Original (unsorted) list for reference:
// export const EXERCISES = [
//   //  Arms
//   "Bicep Curls",
//   "Hammer Curls",
//   "Concentration Curls",
//   "Preacher Curls",
//   "Tricep Pushdowns",
//   "Tricep Dips",
//   "Skull Crushers",
//   "Overhead Tricep Extension",
//   "Cable Curl",
//   "EZ Bar Curl",
//
//   //  Chest
//   "Bench Press",
//   "Incline Bench Press",
//   "Decline Bench Press",
//   "Chest Fly",
//   "Push Ups",
//   "Incline Dumbbell Press",
//   "Cable Chest Crossover",
//   "Machine Chest Press",
//
//   //  Legs
//   "Back Squat",
//   "Front Squat",
//   "Leg Press",
//   "Leg Extensions",
//   "Leg Curls",
//   "Bulgarian Split Squat",
//   "Romanian Deadlift",
//   "Walking Lunges",
//   "Step Ups",
//   "Calf Raises",
//
//   //  Upper Back
//   "Pull Ups",
//   "Lat Pulldown",
//   "Barbell Row",
//   "Seated Cable Row",
//   "Face Pulls",
//   "T-Bar Row",
//   "Single Arm Dumbbell Row",
//
//   //  Lower Back
//   "Deadlift",
//   "Sumo Deadlift",
//   "Back Extensions",
//   "Good Mornings",
//   "Trap Bar Deadlift",
//
//   //  Abdominals
//   "Plank",
//   "Hanging Leg Raises",
//   "Bicycle Crunches",
//   "Cable Crunches",
//   "Russian Twists",
//   "Sit Ups"
// ];

export const EXERCISES = [
  "Back Extensions",
  "Back Squat",
  "Barbell Row",
  "Bench Press",
  "Bicep Curls",
  "Bicycle Crunches",
  "Bulgarian Split Squat",
  "Cable Chest Crossover",
  "Cable Crunches",
  "Cable Curl",
  "Calf Raises",
  "Chest Fly",
  "Concentration Curls",
  "Deadlift",
  "Decline Bench Press",
  "EZ Bar Curl",
  "Face Pulls",
  "Front Squat",
  "Good Mornings",
  "Hammer Curls",
  "Hanging Leg Raises",
  "Incline Bench Press",
  "Incline Dumbbell Press",
  "Lat Pulldown",
  "Leg Curls",
  "Leg Extensions",
  "Leg Press",
  "Machine Chest Press",
  "Overhead Tricep Extension",
  "Plank",
  "Preacher Curls",
  "Pull Ups",
  "Push Ups",
  "Romanian Deadlift",
  "Russian Twists",
  "Seated Cable Row",
  "Single Arm Dumbbell Row",
  "Sit Ups",
  "Skull Crushers",
  "Step Ups",
  "Sumo Deadlift",
  "T-Bar Row",
  "Trap Bar Deadlift",
  "Tricep Dips",
  "Tricep Pushdowns",
  "Walking Lunges"
];
